Repository GrassrootsEconomics/SempoBlockchain, pull requests merged in 2020-05, with the labels that each got.

#39 Missing ussd menu for account create
  app/migrations/versions/50837b220aba_.py
Labels: bug

#40 Short-circuit limits check on balance send
  app/server/utils/transfer_limits.py
  app/server/utils/ussd/token_processor.py
  test/unit/app/utils/ussd/test_token_processor.py
Labels: bug

#35 Default self service user attrs to Unknown
  app/server/utils/user.py
  app/server/utils/ussd/kenya_ussd_processor.py
  app/server/utils/ussd/kenya_ussd_state_machine.py
Labels: patch

#41 Ignore error on duplicate insert for perhaps-seeded account create us…
  app/migrations/versions/0da0913f9dbd_.py
  app/migrations/versions/3500c08573ff_.py
  app/migrations/versions/50837b220aba_.py
Labels: bug

#56 Adds requested changes to receipt messages.
  app/migrations/seed.py
  app/server/locale/ussd.en.yml
  app/server/locale/ussd.sw.yml
  app/server/models/user.py
  app/server/utils/ussd/kenya_ussd_processor.py
  app/server/utils/ussd/kenya_ussd_state_machine.py
  app/server/utils/ussd/token_processor.py
  test/functional/app/api/test_ussd_api.py
  test/unit/app/utils/ussd/kenya/test_pin_state.py
  test/unit/app/utils/ussd/kenya/test_send_state.py
Labels: patch

#32 Improve location handling
  app/Dockerfile
  app/migrations/versions/0da0913f9dbd_.py
  app/migrations/versions/241af81119c4_extended_location_information.py
  app/migrations/versions/984d7e9c50af_.py
  app/migrations/versions/fbc9b56af590_.py
  app/server/models/location.py
  app/server/models/user.py
  app/server/models/user_extension.py
  config.py
  config_files/public/test_config.ini
  invoke_tests.py
  share/location/__init__.py
  share/location/constants.py
  share/location/enum.py
  share/location/osm.py
  test/conftest.py
  test/unit/app/models/test_location.py
  test/unit/share/test_location_osm.py
Labels: enhancement, ready for review

#59 Fix alembic graph to include noop migration step in staging
  app/migrations/versions/0da0913f9dbd_.py
  app/migrations/versions/241af81119c4_extended_location_information.py
  app/migrations/versions/984d7e9c50af_.py
  app/migrations/versions/fbc9b56af590_.py
Labels: bug

#57 Change creation display format.
  app/client/components/dateTime.jsx
Labels: patch

#30 Generic file sync component
  app/Dockerfile
  app/__init__.py
  app/_docker_app_script.sh
  app/run.py
  app/run_with_profile.py
  app/server/__init__.py
  app/server/api/ussd_api.py
  app/server/locale/general_sms.en.yml
  app/server/locale/general_sms.sw.yml
  config.py
  config_files/public/docker_test_config.ini
  config_files/public/test_config.ini
  docker-compose.yml
  files/s3.py
  files/sync.py
  init.py
  test/unit/app/utils/ussd/test_token_processor.py
  test/unit/files/test_files.py
Labels: enhancement

#69 Add SSL redirect
  proxy/default.conf
Labels: ready for review

#71 Trims message length
  app/server/utils/ussd/token_processor.py
  test/functional/app/api/test_ussd_api.py
  test/unit/app/utils/ussd/test_token_processor.py
Labels: patch

#75 Adds hour and minute to user's creation timestamp
  app/client/components/dateTime.jsx
Labels: patch
